import { api } from '@/utils/api'
import { useUser } from '@clerk/nextjs'
import { useRouter } from 'next/router'
import AlbumCard from '@/components/albumCard/AlbumCard'
import Head from 'next/head'

export default function MyRecords() {
  const router = useRouter()
  const { user } = useUser()
  const { userId } = router.query
  const currentUserId = user?.id
  try {
    if (typeof userId !== 'string') throw new Error('Invalid User Id')
    const { data } = api.albums.getAll.useQuery({ userId })

    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center">
          <div className="flex flex-wrap justify-center md:justify-start">
            {data?.map((album) => (
              <AlbumCard
                key={album.id}
                album={album.album}
                cardType={currentUserId === userId ? 'remove' : 'display'}
              />
            ))}
          </div>
        </main>
      </>
    )
  } catch (err) {
    return <div>Something went wrong...</div>
  }
}
